languageCode = "en-us"
title = "CppCast"
theme = "castanet"
BaseURL = "https://cppcast.com/"
paginate = "7"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[params]
custom_css = ["custom.css"]
media_prefix = "https://traffic.libsyn.com/cppcast/"
site_theme = "grey"
site_layout = "row"
enable_jumbo = "false"
truncate = "500"
about_logo = "../img/logo-square.png"
itunes_subscribe = "https://itunes.apple.com/us/podcast/cppcast/id968703120"
spotify_subscribe = "https://open.spotify.com/show/3NPVzS05lvJLv3ovgF3OAP"
google_play_subscribe = "https://podcasts.google.com/feed/aHR0cDovL2NwcGNhc3QubGlic3luLmNvbS9yc3M"
stitcher_subscribe = "https://app.stitcher.com/browse/feed/61449/details"
# rss_subscribe = "http://cppcast.libsyn.com/rss"
disqusShortName = "cppcast"
description = "CppCast is the first podcast for C++ developers by C++ developers!"
favicon = "favicon.ico"

  [params.feed]
    itunes_owner_name = "Rob Irving"
    itunes_image = "../img/logo-square.png"

  [params.social]
    twitter = "cppcast"
    youtube = "channel/UCuCjADS4u3uJDTqUaG0H9dA"
    mastodon = "@mastodon@cppcast.com"

  [params.authors]
    [params.authors.nashp]
      name = "Phil Nash"
      thumbnail = "img/host/phil-nash.jpg"
      bio = "Phil is the original author of Catch2, a regular speaker at conferences, trainer, organizer of C++ on Sea and the C++ London meet-up, and Developer Advocate at SonarSource."
      [params.authors.nashp.social]
        twitter = "phil_nash"

    [params.authors.doumlert]
      name = "Timur Doumler"
      thumbnail = "img/host/timur-doumler.jpg"
      bio = "Timur Doumler is a C++ developer specializing in audio and music technology, active member of the ISO C++ committee, and part of the includecpp.org team. He is passionate about building communities, clean code, good tools, and the evolution of C++."
      [params.authors.doumlert.social]
        twitter = "timur_audio"
  
  [params.sponsors]
    [params.sponsors.jetbrains]
      name = "JetBrains"
      url = "https://jb.gg/cppcast"
      ad = "img/sponsors/jetbrains_600x500.png"

    [params.sponsors.sonar]
      name = "Sonar"
      url = "https://www.sonarsource.com/?utm_source=cppcast&utm_medium=event&utm_campaign=cpp&utm_content=cppcast_ss"
      ad = "img/sponsors/sonar-light-bg.png"

  [params.links]
    [params.links.gear]
      name = "Gear"
      url = "https://shop.spreadshirt.com/CppCast/"
    [params.links.mastodon]
      name = "@mastodon@cppcast.com"
      url = "https://hachyderm.io/@cppcast"

